name: CI/CD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
          
    - name: Enforce Version Update
      run: |
          echo "Checking if library code has changed..."
          git diff -s --exit-code 'origin/master' -- market_toolkit pyproject.toml && exit 0
          echo "Checking if the version has been changed from master..."
          git diff 'origin/master' -- pyproject.toml | grep "+version = "
  
    - name: Build dependencies
      run: |
          python -m pip install --upgrade pip
          pip install poetry==1.1.0b2
          poetry lock
          pip install poetry==1.0.10
          poetry install

      - name: 'Run linting'
        run: |
          poetry run black --check --diff .
          poetry run pylint market_toolkit

      - name: 'Grade code on maintainability and complexity'
        run: |
          poetry run radon cc market_toolkit -s --total-average
          poetry run radon mi market_toolkit -s

  publish:
    name: Publish to PiPy
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'
    steps:

    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install poetry==1.1.0b2
          poetry lock
          pip install poetry==1.0.10
          poetry install

    - name: Build
      run: |
          poetry build
